---
- name: Get Windows LAPS password from AD
  hosts: windows
  gather_facts: no
  tasks:
    - name: Retrieve LAPS password
      win_shell: |
        try {
            Import-Module LAPS
            $computerName = "AURA-VEEAM-01"
            $lapsPassword = Get-LapsADPassword -Identity $computerName

            if ($lapsPassword -ne $null) {
                $plainPassword = $lapsPassword.Password
                # Check if password is a SecureString and convert it if needed
                if ($plainPassword -is [System.Security.SecureString]) {
                    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($plainPassword)
                    $plainPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
                }

                # Convert ExpirationTimestamp to readable string if possible
                $expiration = $lapsPassword.ExpirationTimestamp
                if ($expiration -is [datetime]) {
                    $expiration = $expiration.ToString("yyyy-MM-dd HH:mm:ss")
                }

                $result = [PSCustomObject]@{
                    Name = $computerName
                    Password = $plainPassword
                    ExpirationTimestamp = $expiration
                }
                $result | ConvertTo-Json
            } else {
                $errorObj = [PSCustomObject]@{
                    error = "No LAPS password found"
                }
                $errorObj | ConvertTo-Json
            }
        } catch {
            $errorObj = [PSCustomObject]@{
                error = $_.Exception.Message
            }
            $errorObj | ConvertTo-Json
        }
      register: laps_password_output

    - name: Display LAPS password
      debug:
        msg: "{{ laps_password_output.stdout | from_json }}"
