---
- name: Gather replication summary from all DCs
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin /replsummary
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Show replication summary (raw, synced like AD)
      debug:
        msg: "{{ repl_summary.stdout }}"
      run_once: true