---
- name: Gather replication summary from all DCs
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin /replsummary
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Extract DC lines only
      set_fact:
        repl_lines: "{{ repl_summary.stdout_lines
                        | map('regex_replace', '^[ \t]+', '')
                        | select('match', '^(AURA-DC|[A-Za-z0-9.-]+)[ \t]+[0-9]')
                        | list }}"

    - name: Aggregate all results
      set_fact:
        all_repl: "{{ hostvars
                      | dict2items
                      | map(attribute='value.repl_lines')
                      | select('defined')
                      | sum(start=[]) }}"
      run_once: true

    - name: Split into sources and destinations (safe slicing)
      set_fact:
        source_lines: "{{ all_repl | list | slice((all_repl | length // 2) | int) | first }}"
        dest_lines: "{{ all_repl | list | slice((all_repl | length // 2) | int) | last }}"
      run_once: true

    - name: Show replication summary (full, like AD)
      debug:
        msg: |
          Beginning data collection for replication summary, this may take awhile:
            .....

          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
           {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
           {{ line }}
          {% endfor %}
      run_once: true