---
- name: Gather replication summary from all DCs
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin /replsummary
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Extract DC lines only
      set_fact:
        repl_lines: "{{ repl_summary.stdout_lines
                        | map('regex_replace', '^[ \t]+', '')
                        | select('match', '^(AURA-DC|[A-Za-z0-9.-]+)[ \t]+[0-9]')
                        | list }}"

    - name: Aggregate all results
      set_fact:
        all_repl: "{{ hostvars
                      | dict2items
                      | map(attribute='value.repl_lines')
                      | select('defined')
                      | sum(start=[]) }}"
      run_once: true

    - name: Build list of dicts (DSA + rest)
      set_fact:
        repl_struct: >-
          {{
            all_repl
            | map('regex_replace', '^([A-Za-z0-9.-]+)[ \t]+(.*)', '\\1|\\2')
            | map('split', '|', 1)
            | map('list')
            | list
          }}
      run_once: true

    - name: Split into sources and destinations (mirror order)
      set_fact:
        source_lines: "{{ repl_struct | map('join', ' ') | list }}"
        dest_lines:   "{{ repl_struct | reverse | map('join', ' ') | list }}"
      run_once: true

    - name: Show replication summary (mirrored like AD)
      debug:
        msg: |
          Beginning data collection for replication summary, this may take awhile:
            .....

          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
           {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
           {{ line }}
          {% endfor %}
      run_once: true