---
- name: Check AD replication summary
  hosts: all
  gather_facts: no
  tasks:

    - name: Run repadmin to check replication status
      command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Extract source lines
      set_fact:
        source_lines: >-
          {{ repl_summary.stdout_lines
             | map('regex_replace', '^[ \t]+', '')   # strip leading spaces
             | select('match', '^[A-Za-z0-9.-]+.*[0-9].*\\/.*')
             | list
             | difference(dest_lines | default([])) }}

    - name: Extract destination lines
      set_fact:
        dest_lines: >-
          {{ repl_summary.stdout_lines
             | map('regex_replace', '^[ \t]+', '')   # strip leading spaces
             | select('match', '^[A-Za-z0-9.-]+.*[0-9].*\\/.*')
             | list
             | difference(source_lines | default([])) }}

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {{ source_lines | join('\n') }}

          Destination DSA     largest delta    fails/total %%   error
          {{ dest_lines | join('\n') }}