---
- name: Gather replication summary from all DCs
  hosts: windows
  gather_facts: no

  tasks:
    - name: Run repadmin /replsummary on each DC
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Save clean replication section only
      set_fact:
        repl_output: >-
          {{
            repl_summary.stdout.split('Source DSA')[1]
            | regex_replace('Experienced the following.*','')
            | trim
          }}

- name: Combine and show synchronized replication summary
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build combined replication summary
      set_fact:
        combined_repl: |
          ===== Active Directory Replication Summary (all DCs) =====
          {% for host in groups['windows'] %}
          --- From {{ host }} ---
          {{ hostvars[host].repl_output }}

          {% endfor %}

    - name: Show final synced replication summary
      debug:
        msg: "{{ combined_repl }}"