---
- name: Check AD replication summary
  hosts: windows
  gather_facts: no
  tasks:

    - name: Run repadmin to check replication status
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Extract replication rows
      set_fact:
        repl_lines: >-
          {{ repl_summary.stdout_lines
             | map('regex_replace', '^[ \t]+', '')   # strip leading spaces
             | select('match', '^[A-Za-z0-9.-]+.*[0-9].*\\/.*')
             | list }}

    - name: Split into sources and destinations
      set_fact:
        half: "{{ (repl_lines | length) // 2 }}"
        source_lines: "{{ repl_lines[0:half] }}"
        dest_lines: "{{ repl_lines[half:] }}"

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {{ source_lines | join('\n') }}

          Destination DSA     largest delta    fails/total %%   error
          {{ dest_lines | join('\n') }}