---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_shell: repadmin /replsummary
      register: repl_summary
      ignore_errors: yes

    - name: Extract source lines
      set_fact:
        source_lines: "{{ repl_summary.stdout_lines | select('search','^ *[A-Za-z0-9.-]+.*m:.*s') | list | slice( (repl_summary.stdout_lines | select('search','^Destination DSA') | list | length > 0) | ternary( (repl_summary.stdout_lines | index('Destination DSA')), (repl_summary.stdout_lines|length) ) ) }}"

    - name: Extract destination lines
      set_fact:
        dest_lines: "{{ repl_summary.stdout_lines[ (repl_summary.stdout_lines | map('trim') | list).index('Destination DSA     largest delta    fails/total %%   error') + 1 : ] | select('search','^ *[A-Za-z0-9.-]+.*m:.*s') | list }}"

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
          {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
          {{ line }}
          {% endfor %}