---
- name: Check CPU, memory, and MAC address
  hosts: 10.50.20.58
  gather_facts: no
  tasks:
    - name: Get CPU, memory, and MAC address info
      shell: |
        cpu_cores=$(nproc)
        cpu_model=$(lscpu | grep "Model name" | awk -F: '{print $2}' | sed 's/^ //')
        total_mem=$(free -m | awk '/^Mem:/ { print $2 }')
        used_mem=$(free -m | awk '/^Mem:/ { print $3 }')
        free_mem=$(free -m | awk '/^Mem:/ { print $4 }')
        mac_addr=$(ip link show | awk '/ether/ {print $2; exit}')

        echo "CPU Cores     : $cpu_cores"
        echo "CPU Model     : $cpu_model"
        echo "Total Memory  : ${total_mem} MB"
        echo "Used Memory   : ${used_mem} MB"
        echo "Free Memory   : ${free_mem} MB"
        echo "MAC Address   : $mac_addr"
      register: result

    - name: Show as flat YAML output
      debug:
        msg: |
          {{ result.stdout_lines | join("\n") }}
