---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no
  tasks:

    - name: Run repadmin to check replication status
      win_command: repadmin /replsummary
      register: replsummary
      failed_when: false

    - name: Process replication summary
      set_fact:
        cleaned_summary: >-
          {%- set output = [] -%}
          {%- for line in replsummary.stdout_lines -%}
            {%- set l = line.strip() -%}
            {%- if l != '' and (
                  l.startswith('Beginning data collection') or
                  l.startswith('.....') or
                  l.startswith('Source DSA') or
                  l.startswith('Destination DSA') or
                  (l[0:1].isalpha() and not l.startswith('Experienced') and not l.startswith('Repadmin'))
            ) -%}
              {{- output.append(l) -}}
            {%- endif -%}
          {%- endfor -%}
          {{- output | join('\n') -}}

    - name: Show cleaned replication summary (vertical)
      debug:
        msg: |
          {{ cleaned_summary }}

    - name: Run repadmin to check replication partners
      win_command: repadmin /showrepl
      register: showrepl
      failed_when: false

    - name: Process replication details
      set_fact:
        cleaned_details: >-
          {%- set output = [] -%}
          {%- for line in showrepl.stdout_lines -%}
            {%- set l = line.strip() -%}
            {%- if l != '' -%}
              {%- if l.startswith('Default-First-Site-Name') 
                   or l.startswith('CN=') 
                   or l.startswith('DC=') 
                   or l.startswith('DSA Options:') 
                   or l.startswith('Site Options:') 
                   or l.startswith('DSA object GUID:') 
                   or l.startswith('DSA invocationID:') 
                   or l.startswith('Last attempt') -%}
                {{- output.append(l) -}}
              {%- endif -%}
            {%- endif -%}
          {%- endfor -%}
          {{- output | join('\n') -}}

    - name: Show cleaned replication details (vertical)
      debug:
        msg: |
          {{ cleaned_details }}