---
- name: Check MAC address on Ubuntu
  hosts: ubuntu
  gather_facts: yes  # Automatically gathers facts, including MAC addresses

  tasks:
    - name: Display host's MAC addresses
      debug:
        var: ansible_interfaces

    - name: Display MAC addresses of all interfaces
      debug:
        msg: |
          {% for iface in ansible_interfaces %}
            Interface: {{ iface }}
            MAC Address: {{ hostvars[inventory_hostname]['ansible_' + iface]['macaddress'] }}
          {% endfor %}
