---
- name: Check AD replication summary
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Extract replication rows (strip leading spaces and match valid lines)
      set_fact:
        repl_lines: "{{ repl_summary.stdout_lines
                        | map('regex_replace', '^[ \t]+', '')
                        | select('match', '^[A-Za-z0-9.-]+.*[0-9].*/.*')
                        | list }}"

    - name: Split lines into source and destination
      set_fact:
        half: "{{ (repl_lines | length) // 2 | int }}"
        source_lines: "{{ repl_lines[0:half] }}"
        dest_lines: "{{ repl_lines[half:] }}"

    - name: Show replication summary (formatted like repadmin)
      debug:
        msg: |
          Beginning data collection for replication summary, this may take awhile:
            .....

          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
           {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
           {{ line }}
          {% endfor %}