- name: Check AD Replication
  hosts: all
  gather_facts: no

  tasks:
    - name: Run repadmin replsummary on each DC
      win_command: repadmin /replsummary
      register: repl_output

    - name: Save replication output fact
      set_fact:
        repl_summary: "{{ repl_output.stdout_lines }}"

    - name: Share replication output with localhost
      delegate_to: localhost
      run_once: false
      set_fact:
        all_repl: "{{ all_repl | default({}) | combine({inventory_hostname: repl_summary}) }}"

- name: Format AD-style replication summary
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Build formatted replication summary
      set_fact:
        final_output: |
          Replication Summary Start Time: {{ lookup('pipe', 'date +"%Y-%m-%d %H:%M:%S"') }}

          Beginning data collection for replication summary, this may take awhile:
            .....

          {% for host, rows in all_repl.items() %}
          ===== From {{ host }} =====

          Source DSA          largest delta    fails/total %%   error
          {% for line in rows if line.startswith(" ") and not line.startswith(" Destination") %}
          {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in rows if line.startswith(" ") and not line.startswith(" Source") %}
          {{ line }}
          {% endfor %}

          {% endfor %}

    - name: Print replication summary
      debug:
        msg: "{{ final_output }}"