---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_shell: repadmin /replsummary
      register: repl_summary
      ignore_errors: yes

    - name: Parse only the lines with DSA and delta times
      set_fact:
        repl_lines: "{{ repl_summary.stdout_lines | select('search','[0-9]+m:[0-9]+s') | list }}"

    - name: Determine sources and destinations dynamically
      set_fact:
        half: "{{ (repl_lines | length // 2) | int }}"
        source_lines: "{{ repl_lines[:half] }}"
        dest_lines: "{{ repl_lines[half:] }}"

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
          {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
          {{ line }}
          {% endfor %}