---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no
  tasks:
    - name: Run repadmin to check replication status
      win_command: repadmin /replsummary
      register: replsummary
      failed_when: false

    - name: Show replication summary (clean)
      debug:
        msg: "{{ replsummary.stdout_lines | map('trim') | reject('equalto', '') | join('\n') }}"

    - name: Run repadmin to check replication partners
      win_command: repadmin /showrepl
      register: showrepl
      failed_when: false

    - name: Show replication details (clean)
      debug:
        msg: "{{ showrepl.stdout_lines | map('trim') | reject('equalto', '') | join('\n') }}"