---
- name: Check AD replication summary
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Extract replication rows (strip leading spaces and match valid lines)
      set_fact:
        repl_lines: "{{ repl_summary.stdout_lines
                        | map('regex_replace', '^[ \t]+', '')
                        | select('match', '^[A-Za-z0-9.-]+.*[0-9].*/.*')
                        | list }}"

    - name: Calculate half length
      set_fact:
        half: "{{ (repl_lines | length // 2) | int }}"

    - name: Split into sources and destinations safely
      set_fact:
        source_lines: "{{ repl_lines[0:(half | int)] }}"
        dest_lines: "{{ repl_lines[(half | int):] }}"

    - name: Show replication summary (formatted like repadmin)
      debug:
        msg: |
          Beginning data collection for replication summary, this may take awhile:
            .....

          Source DSA          largest delta    fails/total %%   error
           {{ source_lines | join('\n ') }}

          Destination DSA     largest delta    fails/total %%   error
           {{ dest_lines | join('\n ') }}