---
- name: Get Windows LAPS password from AD
  hosts: windows
  gather_facts: no
  tasks:
    - name: Retrieve LAPS password
      win_shell: |
        try {
            Import-Module LAPS
            $lapsPassword = Get-LapsADPassword -Identity "AURA-VEEAM-01"
            if ($lapsPassword -ne $null) {
                $result = [PSCustomObject]@{
                    Name = $lapsPassword.Name
                    Password = $lapsPassword.Password
                    ExpirationTimestamp = $lapsPassword.ExpirationTimestamp
                }
                $result | ConvertTo-Json
            } else {
                $errorObj = [PSCustomObject]@{
                    error = "No LAPS password found"
                }
                $errorObj | ConvertTo-Json
            }
        } catch {
            $errorObj = [PSCustomObject]@{
                error = $_.Exception.Message
            }
            $errorObj | ConvertTo-Json
        }
      register: laps_password_output

    - name: Display LAPS password
      debug:
        msg: "{{ laps_password_output.stdout | from_json }}"
