---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_shell: repadmin /replsummary
      register: repl_summary
      ignore_errors: yes

    - name: Extract only relevant lines (with delta times)
      set_fact:
        repl_lines: >-
          {{ repl_summary.stdout_lines
             | select('search','[0-9]+m:[0-9]+s')
             | list }}

    - name: Ensure half is an integer
      set_fact:
        half: "{{ (repl_lines | length // 2) | int }}"

    - name: Split into sources and destinations
      set_fact:
        source_lines: "{{ repl_lines | list | slice(0, half) }}"
        dest_lines: "{{ repl_lines | list | slice(half, (repl_lines | length)) }}"

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
          {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
          {{ line }}
          {% endfor %}