---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_shell: repadmin /replsummary
      register: repl_summary
      ignore_errors: yes

    - name: Extract only relevant lines (with delta times)
      set_fact:
        repl_lines: >-
          {{ repl_summary.stdout_lines
             | select('search','[0-9]+m:[0-9]+s')
             | list | default([]) }}

    - name: Debug parsed replication lines
      debug:
        var: repl_lines

    - name: Ensure half is safe integer
      set_fact:
        half: "{{ (repl_lines | length > 0) | ternary(((repl_lines | length) // 2), 0) }}"

    - name: Split into sources and destinations safely
      set_fact:
        source_lines: "{{ repl_lines[0:half] if half > 0 else [] }}"
        dest_lines: "{{ repl_lines[half:] if half > 0 else [] }}"

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
          {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
          {{ line }}
          {% endfor %}