---
- name: Gather replication summary from all DCs
  hosts: windows
  gather_facts: no

  tasks:
    - name: Run repadmin /replsummary on each DC
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Store each host's replication output
      set_fact:
        repl_results: "{{ repl_results | default({}) | combine({inventory_hostname: repl_summary.stdout}) }}"

    - name: Show combined replication summary per DC
      run_once: true
      debug:
        msg: |
          {% for host, output in repl_results.items() %}
          ===== Replication Summary from {{ host }} =====
          {{ output }}

          {% endfor %}