---
- name: Gather replication summary from all DCs
  hosts: windows
  gather_facts: no

  tasks:
    - name: Run repadmin /replsummary on each DC
      win_command: repadmin /replsummary
      register: repl_summary
      changed_when: false

    - name: Save each host's result in hostvars
      set_fact:
        repl_output: "{{ repl_summary.stdout }}"

- name: Combine and show replication summary (all DCs)
  hosts: windows
  gather_facts: no
  tasks:
    - name: Show combined replication summaries
      debug:
        msg: |
          {% for host in groups['windows'] %}
          ===== Replication Summary from {{ host }} =====
          {{ hostvars[host].repl_output }}

          {% endfor %}