- name: Get essential AD user details
  hosts: windows
  gather_facts: no
  vars:
    ad_username: "del"   # change this to your AD username
  tasks:
    - name: Get user basic info
      win_shell: |
        $user = Get-ADUser -Identity "{{ ad_username }}" -Properties MemberOf
        $ou = ($user.DistinguishedName -split ',')[1..($user.DistinguishedName -split ',').Length] -join ','
        $groups = $user.MemberOf | ForEach-Object { (Get-ADGroup $_).Name }
        [PSCustomObject]@{
            Name = $user.Name
            Username = $user.SamAccountName
            OU = $ou
            Groups = $groups -join ', '
        }
      register: ad_user_info

    - name: Show user details
      debug:
        var: ad_user_info.stdout_lines