---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no

  tasks:

    - name: Run repadmin to check replication status
      win_shell: repadmin /replsummary
      register: repl_summary
      ignore_errors: yes

    - name: Extract only relevant lines (skip noise)
      set_fact:
        repl_lines: >-
          {{ repl_summary.stdout_lines
             | select('search','^[A-Za-z0-9.-]+.*[0-9]+m:[0-9]+s')
             | list }}

    - name: Calculate half as integer
      set_fact:
        half: "{{ (repl_lines | length // 2) | int }}"

    - name: Build source_lines list
      set_fact:
        source_lines: "{{ repl_lines | zip(range(0, repl_lines|length)) 
                          | selectattr('1','lt',half) 
                          | map(attribute='0') 
                          | list }}"

    - name: Build dest_lines list
      set_fact:
        dest_lines: "{{ repl_lines | zip(range(0, repl_lines|length)) 
                        | selectattr('1','ge',half) 
                        | map(attribute='0') 
                        | list }}"

    - name: Show cleaned replication summary
      debug:
        msg: |
          Source DSA          largest delta    fails/total %%   error
          {% for line in source_lines %}
          {{ line }}
          {% endfor %}

          Destination DSA     largest delta    fails/total %%   error
          {% for line in dest_lines %}
          {{ line }}
          {% endfor %}