---
- name: Check CPU, memory, and MAC address
  hosts: 10.50.20.58
  gather_facts: no
  tasks:
    - name: Get CPU, memory, and MAC address info
      shell: |
        cpu_cores=$(nproc)
        cpu_model=$(lscpu | grep "Model name" | awk -F: '{print $2}' | sed 's/^ //')
        total_mem=$(free -m | awk '/^Mem:/ { print $2 }')
        used_mem=$(free -m | awk '/^Mem:/ { print $3 }')
        free_mem=$(free -m | awk '/^Mem:/ { print $4 }')
        mac_addr=$(ip link show | awk '/ether/ {print $2; exit}')

        echo "CPU_Cores: $cpu_cores"
        echo "CPU_Model: \"$cpu_model\""
        echo "Memory_Total_MB: $total_mem"
        echo "Memory_Used_MB: $used_mem"
        echo "Memory_Free_MB: $free_mem"
        echo "MAC_Address: \"$mac_addr\""
      register: result

    - name: Show vertical output
      debug:
        msg: "{{ result.stdout }}"
