- name: Get AD user details with additional info
  hosts: windows
  gather_facts: no
  vars:
    ad_name: "test2"
  tasks:
    - name: Get user by name
      win_shell: |
        $user = Get-ADUser -Filter "Name -like '*{{ ad_name }}*'" -Properties MemberOf, Description, Office, TelephoneNumber, Mail
        if ($user) {
            $ou = ($user.DistinguishedName -split ',')[1..($user.DistinguishedName -split ',').Length] -join ','
            $groups = $user.MemberOf | ForEach-Object { (Get-ADGroup $_).Name } | Sort-Object

            $details = @()
            $details += "Name           : $($user.Name)"
            $details += "Username       : $($user.SamAccountName)"
            $details += "OU             : $ou"
            $details += "Groups         : $($groups -join ', ')"
            $details += "Description    : $($user.Description)"
            $details += "Office         : $($user.Office)"
            $details += "Telephone      : $($user.TelephoneNumber)"
            $details += "Email          : $($user.Mail)"

            # Force into single line with custom delimiter
            Write-Output ($details -join ' | ')
        } else {
            Write-Output "User not found"
        }
      register: ad_user_info

    - name: Show user details
      debug:
        msg: "{{ ad_user_info.stdout }}"