- name: Show MAC addresses on Linux hosts
  hosts: ubuntu
  gather_facts: yes

  tasks:
    - name: Display MAC addresses of all interfaces
      debug:
        msg: |
          {% for iface in ansible_interfaces %}
          Interface {{ iface }}: {{ hostvars[inventory_hostname]['ansible_' + iface].macaddress | default('N/A') }}
          {% endfor %}
