---
- name: Get MAC address and hostname from Windows Server
  hosts: windows
  gather_facts: no

  tasks:
    - name: Get hostname
      win_shell: hostname
      register: hostname_result

    - name: Get MAC address using PowerShell
      win_shell: |
        Get-NetAdapter | Select-Object -Property Name, MacAddress
      register: mac_info

    - name: Display hostname
      debug:
        msg: "Hostname: {{ hostname_result.stdout }}"

    - name: Display MAC address
      debug:
        var: mac_info.stdout_lines
