---
- name: Check Active Directory Replication
  hosts: windows
  gather_facts: no
  tasks:

    - name: Run repadmin to check replication status
      win_command: repadmin /replsummary
      register: replsummary
      failed_when: false

    - name: Process replication summary into list
      set_fact:
        cleaned_summary_list: >-
          {%- set output = [] -%}
          {%- for line in replsummary.stdout_lines -%}
            {%- set l = line.strip() -%}
            {%- if l != '' and (
                  l.startswith('Replication Summary Start Time') or
                  l.startswith('Beginning data collection') or
                  l.startswith('.....') or
                  l.startswith('Source DSA') or
                  l.startswith('Destination DSA') or
                  (l[0:1].isalpha() and not l.startswith('Experienced') and not l.startswith('Repadmin'))
            ) -%}
              {{- output.append(l) -}}
            {%- endif -%}
          {%- endfor -%}
          {{ output }}

    - name: Show cleaned replication summary (vertical)
      debug:
        msg: |
          {% for line in cleaned_summary_list %}
          {{ line }}
          {% endfor %}

    - name: Run repadmin to check replication partners
      win_command: repadmin /showrepl
      register: showrepl
      failed_when: false

    - name: Process replication details into structured list
      set_fact:
        cleaned_details_list: >-
          {%- set output = [] -%}
          {%- set current_dc = '' -%}
          {%- for line in showrepl.stdout_lines -%}
            {%- set l = line.strip() -%}
            {%- if l != '' -%}
              {%- if l.startswith('Default-First-Site-Name') -%}
                {{- output.append("\n" + l) -}}
                {%- set current_dc = l -%}
              {%- elif l.startswith('CN=') or l.startswith('DC=') -%}
                {{- output.append("  Partition: " + l) -}}
              {%- elif l.startswith('DSA Options:') or l.startswith('Site Options:') or l.startswith('DSA object GUID:') or l.startswith('DSA invocationID:') -%}
                {{- output.append("    " + l) -}}
              {%- elif l.startswith('Last attempt') -%}
                {{- output.append("    " + l) -}}
              {%- endif -%}
            {%- endif -%}
          {%- endfor -%}
          {{ output }}

    - name: Show cleaned replication details (vertical)
      debug:
        msg: |
          {% for line in cleaned_details_list %}
          {{ line }}
          {% endfor %}