---
- name: Create an AD User with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure Marie Floria exists
      microsoft.ad.user:
        identity: marie
        name: Marie Floria
        user_principal_name: marie@yourdomain.com
        password: Welcome1
        enabled: yes
        state: present
