---
- name: Create an AD User with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure Marie Floria exists
      microsoft.ad.user:
        identity: marie
        name: Marie Floria
        sam_account_name: marie
        firstname: Marie
        surname: Floria
        display_name: Marie Floria
        upn: marie@aura.local
        password: Welcome1
        enabled: yes
        state: present
        path: "OU=Users,OU=KMC,DC=aura,DC=local"
        email: marieflora@outlook.com
        description: Client
        company: aura
        telephoneNumber: "99999999"
        physicalDeliveryOfficeName: "HQ Office"
