---
- name: Create an AD User with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure Marie Floria exists
      microsoft.ad.user:
        identity: marie
        name: Marie Floria
        upn: marie@yourdomain.com
        password: Welcome1
        enabled: yes
        state: present
        path: "OU=Users,OU=KMC,DC=aura,DC=local"
