---
- name: Create an AD User with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create user in AD
      microsoft.ad.user:
        identity: test2
        name: test2
        sam_account_name: test2
        firstname: test2
        surname: test2
        display_name: test2
        upn: test2@aura.local
        password: Welcome1
        enabled: yes
        state: present
        path: "OU=Users,OU=MDS,DC=aura,DC=local"
        email: test1@outlook.com
        description: Client
        company: aura
        attributes:
          set:
            telephoneNumber: 99999999
            physicalDeliveryOfficeName: HQ Office

    - name: Set Username
      set_fact:
        sam_account_name: "test2"

    - name: Add user to group Local Administrator
      microsoft.ad.group:
        name: "MDS_MIS"
        path: "OU=Security Group,OU=MDS,DC=aura,DC=local"
        members:
          add:
            - "{{ sam_account_name }}"
        state: present

    - name: Add user to group NOC Team
      microsoft.ad.group:
        name: "MDS_NDC"
        path: "OU=Security Group,OU=MDS,DC=aura,DC=local"
        members:
          add:
            - "{{ sam_account_name }}"
        state: present
