---
- name: Create an AD User with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create user in AD
      microsoft.ad.user:
        identity: cdr
        name: Chris Del Rosario
        sam_account_name: cdr
        firstname: Chris
        surname: Del Rosario
        display_name: Chris Del Rosario
        upn: cdr@aura.local
        password: Welcome1
        enabled: yes
        state: present
        path: "OU=Users,OU=MDS,DC=aura,DC=local"
        email: cdr@outlook.com
        description: Systems Engineer
        attributes:
          set:
            telephoneNumber: 09090909
            physicalDeliveryOfficeName: HQ Office

    - name: Set Username
      set_fact:
        sam_account_name: "cdr"

    - name: Add user to group MIS
      microsoft.ad.group:
        name: "MDS_MIS"
        path: "OU=Security Group,OU=MDS,DC=aura,DC=local"
        members:
          add:
            - "{{ sam_account_name }}"
        state: present

    - name: Add user to group NDC
      microsoft.ad.group:
        name: "MDS_NDC"
        path: "OU=Security Group,OU=MDS,DC=aura,DC=local"
        members:
          add:
            - "{{ sam_account_name }}"
        state: present
