---
- name: Create an AD User with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: User Added
      microsoft.ad.user:
        identity: nadz
        name: Nadz Mekhan
        sam_account_name: nadz
        firstname: Nadz
        surname: Mekhan
        display_name: Nadz Mekhan
        upn: nadz@aura.local
        password: Welcome1
        enabled: yes
        state: present
        path: "OU=Users,OU=KMC,DC=aura,DC=local"
        email: nadz@outlook.com
        description: Client
        company: aura
        add_group: IT_LA
        attributes:
          set:
            telephoneNumber: 99999999
            physicalDeliveryOfficeName: HQ Office
