apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: kt-website
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Christopher Del Rosario
