- name: Test Email Notification
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Print test message
      debug:
        msg: "This is a Semaphore email test run at {{ lookup('pipe', 'date') }}"
