---
- name: Check Veeam Backup & Replication job status
  hosts: veeam_server
  gather_facts: no

  tasks:
    - name: Ensure Veeam PowerShell module is loaded
      win_shell: |
        $modulePath = "C:\Program Files\Veeam\Backup and Replication\Console\Veeam.Backup.PowerShell\Veeam.Backup.PowerShell.psd1"
        if (Test-Path $modulePath) {
            Import-Module $modulePath -ErrorAction Stop
            Write-Output "Veeam PowerShell module loaded successfully."
        } else {
            Write-Error "Veeam PowerShell module not found at $modulePath"
        }

    - name: Get readable Veeam backup job status with restore point count
      win_shell: |
        Import-Module "C:\Program Files\Veeam\Backup and Replication\Console\Veeam.Backup.PowerShell\Veeam.Backup.PowerShell.psd1" -ErrorAction Stop

        $sessions = Get-VBRBackupSession | Sort-Object EndTime -Descending | Select-Object -First 10
        $backups = Get-VBRBackup
        $results = @()

        foreach ($session in $sessions) {
            $status = switch ($session.Result.ToString()) {
                "Success" { "Success" }
                "Warning" { "Warning" }
                "Failed"  { "Failed" }
                default   { "Unknown ($($session.Result))" }
            }

            # Try to find backup matching the job
            $backup = $backups | Where-Object { $_.JobName -eq $session.JobName }
            $rpCount = if ($backup) { ($backup | Get-VBRRestorePoint).Count } else { 0 }

            $results += [PSCustomObject]@{
                "Job Name"      = $session.JobName
                "Result"        = $status
                "RestorePoints" = [int]$rpCount
                "StartTime"     = $session.CreationTime.ToString("yyyy-MM-dd HH:mm:ss")
                "EndTime"       = $session.EndTime.ToString("yyyy-MM-dd HH:mm:ss")
            }
        }

        $results | ConvertTo-Json -Compress
      register: veeam_jobs

    - name: Display Veeam backup job status with restore count
      debug:
        msg: "{{ veeam_jobs.stdout | from_json }}"