---
- name: Check Veeam Backup & Replication job status
  hosts: 10.50.20.53
  gather_facts: no
  vars:
    veeam_snapin: "VeeamPSSnapIn"

  tasks:
    - name: Ensure Veeam PowerShell snap-in is loaded
      win_shell: |
        if (-not (Get-PSSnapin -Name {{ veeam_snapin }} -ErrorAction SilentlyContinue)) {
          Add-PSSnapin {{ veeam_snapin }}
        }

    - name: Get last 10 Veeam backup job sessions
      win_shell: |
        Add-PSSnapin {{ veeam_snapin }} -ErrorAction SilentlyContinue
        $sessions = Get-VBRBackupSession | Sort-Object EndTime -Descending | Select-Object -First 10
        $output = @()
        foreach ($s in $sessions) {
          $output += [PSCustomObject]@{
            JobName = $s.JobName
            State = $s.State
            Result = $s.Result
            StartTime = $s.CreationTime
            EndTime = $s.EndTime
          }
        }
        $output | ConvertTo-Json -Depth 2
      register: veeam_sessions

    - name: Display Veeam backup job status
      debug:
        msg: "{{ veeam_sessions.stdout | from_json }}"