---
- name: Check Veeam Backup & Replication job status
  hosts: veeam_server
  gather_facts: no

  tasks:
    - name: Import Veeam PowerShell module
      win_shell: |
        Import-Module Veeam.Backup.PowerShell -ErrorAction Stop

    - name: Get last 10 Veeam backup job sessions
      win_shell: |
        Import-Module Veeam.Backup.PowerShell -ErrorAction SilentlyContinue
        $sessions = Get-VBRBackupSession | Sort-Object EndTime -Descending | Select-Object -First 10
        $output = @()
        foreach ($s in $sessions) {
          $output += [PSCustomObject]@{
            JobName = $s.JobName
            State = $s.State
            Result = $s.Result
            StartTime = $s.CreationTime
            EndTime = $s.EndTime
          }
        }
        $output | ConvertTo-Json -Depth 2
      register: veeam_sessions

    - name: Display Veeam backup job status
      debug:
        msg: "{{ veeam_sessions.stdout | from_json }}"